name: Update Citation Count

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_citation_count:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install scholarly

    - name: Get Citation Count
      run: python get_citation_count.py

